spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:docmind}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          model: gemini-2.5-flash
          temperature: 0.2

        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001

    vectorstore:
      pgvector:
        index-type: NONE
        distance-type: COSINE_DISTANCE
        dimensions: 3072
        table-name: vector_store
        schema-name: public
        initialize-schema: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 50MB



#app configurations
app:
  rag:
    chunk-size: 700
    #app.rag.chunk-size: 700: When parsing a large document (like a PDF), the system splits it into smaller snippets of 700 tokens/characters before embedding them.
#    chunk-overlap: 100     (Commented out) If active, it would overlap adjacent chunks by 100 characters to prevent cutting off sentences mid-thought across chunk boundaries.
    top-k: 5
    #When a user asks a question, the vector database will fetch the top 5 most relevant document chunks to feed to the LLM as context.
    similarity-threshold: 0.0
    #app.rag.similarity-threshold: 0.0: The minimum matching score required to retrieve a chunk. Set to 0.0, meaning it will return the closest 5 chunks regardless of how poor the match quality is.

  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    #app.cors.allowed-headers: "*": Allows external clients to send any custom HTTP headers (like Authorization) in their API requests.


#jwt configurations


jwt:
  secret: ${JWT_SECRET:sdafasfasfasdhfojhascapfdaDHAfbashfabfashfasbfshfdasfhqf}
  expiration: 3600000


bootui:
  enabled: ON


logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
#logging.level.org.springframework.ai.chat.client.advisor: DEBUG: Changes the logging verbosity for Spring AI Advisors to the DEBUG level. This will print deep internal steps to your console—such as the exact prompt modifications, memory injection, and context retrieval history—making it incredibly helpful for debugging RAG prompt flows.
