import { Template } from "@/types";

export const FEATURE_TEMPLATES: Template[] = [
  {
    id: "clause-indemnity",
    category: "clauses",
    title: "Indemnity & Liability Cap",
    badge: "Key Clauses",
    iconName: "ShieldAlert",
    description: "Extract and evaluate indemnification clauses, liability caps, and carve-outs.",
    prompt: "Extract and analyze all clauses related to Indemnification, Limitation of Liability, and any exceptions/carve-outs. For each, cite the exact page/section and provide a concise risk assessment.",
    suggestedTopK: 8,
  },
  {
    id: "clause-termination",
    category: "clauses",
    title: "Termination & Breach Rights",
    badge: "Key Clauses",
    iconName: "FileWarning",
    description: "Identify notice periods, cure rights, termination for convenience, and cause triggers.",
    prompt: "Identify all Termination provisions in the document. What are the notice periods, cure periods, termination for cause triggers, and survival obligations upon termination?",
    suggestedTopK: 6,
  },
  {
    id: "clause-confidentiality",
    category: "clauses",
    title: "Confidentiality & NDA Scope",
    badge: "Key Clauses",
    iconName: "Lock",
    description: "Map definitions of confidential info, exclusions, standard of care, and duration.",
    prompt: "Analyze the Confidentiality obligations. What qualifies as confidential information, what exclusions apply, what standard of care is required, and what is the survival term?",
    suggestedTopK: 6,
  },
  {
    id: "clause-ip-governing",
    category: "clauses",
    title: "IP Rights & Governing Law",
    badge: "Key Clauses",
    iconName: "Scale",
    description: "Check intellectual property assignment, licenses granted, jurisdiction, and arbitration venue.",
    prompt: "Summarize the Intellectual Property ownership/license terms and the Governing Law & Dispute Resolution clauses. Note which state/country law governs and whether arbitration is mandatory.",
    suggestedTopK: 5,
  },
  {
    id: "facts-dates-deadlines",
    category: "facts",
    title: "Deadlines, Dates & Milestones",
    badge: "Fact Finder",
    iconName: "CalendarClock",
    description: "Extract all temporal commitments, effective dates, renewal windows, and delivery dates.",
    prompt: "Extract all key dates, effective dates, renewal windows, delivery deadlines, and performance milestones mentioned across the document with citations.",
    suggestedTopK: 8,
  },
  {
    id: "facts-entities-signatories",
    category: "facts",
    title: "Parties & Signatories Audit",
    badge: "Fact Finder",
    iconName: "Users",
    description: "Identify all legal entities, subsidiaries, signatories, and authorized representatives.",
    prompt: "Who are all the legal entities, contracting parties, subsidiaries, and authorized signatories named in the document? List their official legal names and roles.",
    suggestedTopK: 5,
  },
  {
    id: "financial-metrics",
    category: "financial",
    title: "Fees, Pricing & Payments",
    badge: "Financial",
    iconName: "Coins",
    description: "Isolate fee schedules, payment terms, late penalties, price adjustment mechanisms, and taxes.",
    prompt: "Break down all financial terms, pricing models, payment terms (e.g. Net 30), penalties for late payment, and any price increase or inflation adjustment clauses.",
    suggestedTopK: 7,
  },
  {
    id: "risk-compliance-audit",
    category: "risk",
    title: "Legal Risk & Red Flags",
    badge: "Risk Audit",
    iconName: "AlertTriangle",
    description: "Identify non-standard clauses, one-sided covenants, and unusual liabilities.",
    prompt: "Conduct a comprehensive Red Flag Risk Audit of this document. Identify any non-standard covenants, one-sided terms, unlimited liabilities, missing warranties, or operational risks.",
    suggestedTopK: 10,
  },
  {
    id: "summary-executive",
    category: "summary",
    title: "Executive Summary & Actions",
    badge: "Executive",
    iconName: "Briefcase",
    description: "Generate a high-impact, C-level executive summary with actionable takeaways.",
    prompt: "Provide a comprehensive Executive Summary of this document. Structure it with: 1) Core Purpose, 2) Key Obligations of Each Party, 3) Critical Highlights, and 4) Action Items.",
    suggestedTopK: 10,
  },
  {
    id: "summary-faq",
    category: "summary",
    title: "FAQ & Knowledge Base",
    badge: "Knowledge Base",
    iconName: "HelpCircle",
    description: "Generate the top 10 most common questions and answers derived from the document.",
    prompt: "Based on the content of the document, generate the top 8 most frequent and critical Questions & Answers (FAQ) that a stakeholder or customer would ask.",
    suggestedTopK: 8,
  },
];
